// Generated by zipx. Do not edit. Run 'sbt zipxWorkflowGenerate' to regenerate.
addSbtPlugin("rocks.earlyeffect" % "sbt-zipx" % "0.7.3")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.22.0")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.6.2")
addSbtPlugin("rocks.earlyeffect" % "sbt-dynver-ci" % "0.2.3")
addSbtPlugin("rocks.earlyeffect" % "sbt-splice" % "0.1.0")
addSbtPlugin("rocks.earlyeffect" % "sbt-ascent-preview" % "0.5.0")
